# Part 2. Run the detector/classifier

## Part 2a. Feature extraction
```{r , message= FALSE }
  library(gibbonR)

# Change this so that it points to the location on your computer
FolderPath <- '/Users/denaclink/Library/CloudStorage/Box-Box/gibbonRSampleFiles/'

# Specify the folder where the training data were saved
TrainingDataFolderLocation <- paste(FolderPath,"/TrainingDataFromRavenSelectionTables/",
                                    sep='')
  
TrainingDataMFCC <- MFCCFunction(input.dir= TrainingDataFolderLocation, min.freq = 400, max.freq = 1600,win.avg="standard")
  
TrainingDataMFCC$class <- as.factor(TrainingDataMFCC$class)
```
  
## Part 2b. Run the detector/classifier using the 'gibbonR' function.  
```{r }
  library(gibbonR)

  # Specify the folder where the training data will be saved
TestFileDirectory <- paste(FolderPath,"/GibbonTestFiles/",
                                    sep='')

# Specify output directory
OutputDirectory <-  "data/DetectAndClassifyOutput"

# Create if doesn't exist  
dir.create(OutputDirectory,recursive = TRUE)

 
# Run the function to detect and classify  
gibbonR(input=TestFileDirectory,
          input.type = 'directory',
                    feature.df=TrainingDataMFCC,
                    model.type.list=c('SVM'), # Can specify SVM or RF 
                    tune = TRUE,
                    short.wav.duration=300,
                    target.signal = c("female.gibbon"),
                    min.freq = 400, max.freq = 1600,
                    noise.quantile.val=0.15,
                    minimum.separation =3,
                    n.windows = 9, num.cep = 12,
                    spectrogram.window =160,
                    pattern.split = ".wav",
                    min.signal.dur = 3,
                    max.sound.event.dur = 25,
                    maximum.separation =1,
                    probability.thresh.svm = 0.15,
                    probability.thresh.rf = 0.15,
                    wav.output = "FALSE",
                    output.dir =OutputDirectory,
                    swift.time=TRUE,time.start=5,time.stop=10,
                    write.table.output=TRUE,verbose=TRUE,
                    random.sample='NA')
  
  

```

